#requires -Version 7.3

<#
.SYNOPSIS
    Capture a matrix of short commands, each run repeatedly inside one ETW session, then
    write a capture manifest the filtrace batch and diff verbs read.

.DESCRIPTION
    A short command is the hardest thing to profile honestly. Starting and flushing an ETW
    session costs far more than a 30-100 ms process takes to run, so capturing one
    invocation yields a trace that is mostly capture overhead with too few samples to rank.
    This runs each scenario N times inside a single session: the session cost is paid once
    per scenario, one trace is converted instead of many thin ones, and the samples add up
    to something rankable.

    Each scenario becomes one case in a `manifest.json` of kind `command`, so
    `filtrace batch` ranks the whole matrix in one call and `filtrace diff` pairs two runs
    of it by scenario name. Every launch is recorded with its root process id and window,
    which is what lets an analysis attribute work to a particular run rather than to the
    scenario as a whole.

    ETW is machine-wide and needs Administrator, so this self-elevates once for the whole
    matrix rather than per scenario - one UAC prompt no matter how many scenarios run.

    A scenario that fails does not discard the run: it is recorded as a warning and the
    manifest is written with the cases that did succeed, so a long matrix is not lost to
    one bad command. If every scenario fails, the diagnostic manifest contains no
    analyzable cases and the script exits 1.

    filtrace: https://github.com/JeremyKuhne/filtrace - install once with
    `dotnet tool install -g KlutzyNinja.Filtrace`, or drive the MCP trace_* tools.

.PARAMETER Scenario
    The commands to capture. Each entry is a hashtable with Name, Command, and either
    optional legacy Arguments text or an ArgumentList string array, for example:

        -Scenario @(
            @{ Name = 'version'; Command = 'dotnet'; Arguments = '--version' },
            @{ Name = 'build'; Command = 'dotnet'; ArgumentList = @('build', '--no-restore') })

    ArgumentList preserves spaces, quotes, and empty arguments through the collector's
    Windows command-line boundary. Legacy Arguments remains an opaque command line and
    is not presented as parsed argv. Names must be unique; they are the case identity
    that diff pairs on. Names may contain ordinary dots and spaces, but must fit the
    manifest case-id limit and be valid non-reserved Windows filename components.

.PARAMETER Iterations
    How many times to launch each command inside its session. Default 25, which is enough
    for a 30-100 ms command to clear the sample count filtrace treats as directional.

.PARAMETER CaptureProfile
    Capture profile: startup (default), cpu, or threadtime. `startup` enables only the
    keywords a startup and CPU analysis reads, which is the lowest-perturbation choice for
    a short command.

.PARAMETER CpuSampleMSec
    CPU sample interval in milliseconds. Default 1 (the ETW default). A 30-100 ms command
    gets only tens of samples at 1 ms, so lower it - sub-millisecond sampling is honored,
    down to roughly 0.12 ms on the Windows 11 machine this was measured on - and the
    manifest records what was requested against what the machine actually honored.

.PARAMETER OutputDirectory
    Run directory for the traces, manifest, and log. Defaults to a run-stamped directory
    under ./perf-traces.

.PARAMETER SymbolsDirectory
    Optional build-output directory recorded against every case, so batch and diff resolve
    source lines without being told again.

.PARAMETER FiltracePath
    Path to a specific filtrace executable. Defaults to the one on PATH. Point this at a
    local build when testing changes to the tool itself, or when the installed version is
    older than the options this script needs.

.PARAMETER ElevatedTimeoutSeconds
    How long the non-elevated parent waits for the elevated child before giving up.
    Default 1800 (30 minutes).

.PARAMETER SpecPath
    Internal. Set on the elevated relaunch to point at the serialized scenario matrix.

.PARAMETER ExpectedSpecSha256
    Internal. SHA-256 of the exact serialized scenario matrix bytes generated by the parent.

.PARAMETER LogFile
    Internal. Set on the elevated relaunch so the calling console can surface the output.

.EXAMPLE
    ./Capture-CommandTrace.ps1 -Scenario @(@{ Name='version'; Command='dotnet'; Arguments='--version' })

.EXAMPLE
    ./Capture-CommandTrace.ps1 -Scenario $matrix -Iterations 50 -CaptureProfile cpu
#>
param(
    [hashtable[]]$Scenario,
    [ValidateRange(1, 1000)][int]$Iterations = 25,
    [ValidateSet('startup', 'cpu', 'threadtime')][string]$CaptureProfile = 'startup',
    [ValidateRange(0.01, 1000.0)][double]$CpuSampleMSec = 1.0,
    [string]$OutputDirectory,
    [string]$SymbolsDirectory,
    [string]$FiltracePath,
    [ValidateRange(1, 2147483647)][int]$ElevatedTimeoutSeconds = 1800,
    [string]$SpecPath,
    [ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ExpectedSpecSha256,
    [string]$LogFile
)

$ErrorActionPreference = 'Stop'
$script:PSNativeCommandArgumentPassing = 'Standard'
$PSNativeCommandUseErrorActionPreference = $false
$invocationWorkingDirectory = [System.IO.Path]::GetFullPath((Get-Location).Path)
$maxCaptureCases = 256
$maxCaseIdLength = 256
$maxTraceFileNameLength = 255
$maxSerializedBytes = 16 * 1024 * 1024

function Test-Elevated {
    $identity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    try {
        $principal = New-Object System.Security.Principal.WindowsPrincipal($identity)
        return $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
    }
    finally {
        $identity.Dispose()
    }
}

function ConvertTo-WindowsCommandLineArgument([string]$Value) {
    if ($Value.Length -gt 0 -and $Value -notmatch '[\s"]') { return $Value }

    $builder = [System.Text.StringBuilder]::new()
    [void]$builder.Append('"')
    $backslashes = 0
    foreach ($character in $Value.ToCharArray()) {
        if ($character -eq '\') {
            $backslashes++
            continue
        }

        if ($character -eq '"') {
            [void]$builder.Append('\', ($backslashes * 2) + 1)
        }
        else {
            [void]$builder.Append('\', $backslashes)
        }

        [void]$builder.Append($character)
        $backslashes = 0
    }

    [void]$builder.Append('\', $backslashes * 2)
    [void]$builder.Append('"')
    return $builder.ToString()
}

function Join-WindowsCommandLine([string[]]$ArgumentList) {
    return (($ArgumentList | ForEach-Object { ConvertTo-WindowsCommandLineArgument $_ }) -join ' ')
}

function Resolve-ExecutableIdentity([string]$Command) {
    $resolvedPath = $null
    if ([System.IO.Path]::IsPathRooted($Command) -or
        $Command.IndexOf([System.IO.Path]::DirectorySeparatorChar) -ge 0 -or
        $Command.IndexOf([System.IO.Path]::AltDirectorySeparatorChar) -ge 0) {
        if (Test-Path -LiteralPath $Command -PathType Leaf) {
            $resolvedPath = [System.IO.Path]::GetFullPath($Command)
        }
    }
    else {
        $resolvedCommand = Get-Command $Command -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($null -ne $resolvedCommand) { $resolvedPath = [System.IO.Path]::GetFullPath($resolvedCommand.Source) }
    }

    if (-not $resolvedPath) { throw "Executable '$Command' was not found as an application or literal file path." }
    return [ordered]@{
        path   = $resolvedPath
        sha256 = (Get-FileHash -LiteralPath $resolvedPath -Algorithm SHA256).Hash.ToLowerInvariant()
    }
}

function Get-FiltraceIdentity([string]$RequestedPath) {
    $requested = $RequestedPath
    if (-not $requested) { $requested = 'filtrace' }
    $identity = Resolve-ExecutableIdentity $requested
    $versionOutput = & $identity.path --version 2>&1 | Out-String
    $versionExitCode = $LASTEXITCODE
    if ($versionExitCode -ne 0) {
        throw "Resolved filtrace '$($identity.path)' failed --version with exit $versionExitCode."
    }

    $version = $versionOutput.Trim()
    if ([string]::IsNullOrWhiteSpace($version)) {
        throw "Resolved filtrace '$($identity.path)' returned an empty --version result."
    }
    if ($version.Length -gt 1024) {
        throw "Resolved filtrace '$($identity.path)' returned an unexpectedly large --version result."
    }

    return [ordered]@{
        path    = $identity.path
        sha256  = $identity.sha256
        version = $version
    }
}

function Get-Sha256Text([string]$Text) {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
    $hash = [System.Security.Cryptography.SHA256]::HashData($bytes)
    return [Convert]::ToHexString($hash).ToLowerInvariant()
}

function Read-AuthenticatedSpec([string]$Path, [string]$ExpectedSha256) {
    if ([string]::IsNullOrWhiteSpace($ExpectedSha256)) {
        throw 'ExpectedSpecSha256 is required when SpecPath is supplied.'
    }

    $stream = [System.IO.File]::Open(
        $Path,
        [System.IO.FileMode]::Open,
        [System.IO.FileAccess]::Read,
        [System.IO.FileShare]::Read)
    try {
        if ($stream.Length -gt $maxSerializedBytes) {
            throw "Capture specification exceeds the $maxSerializedBytes-byte limit."
        }

        [byte[]]$bytes = [byte[]]::new([int]$stream.Length)
        $offset = 0
        while ($offset -lt $bytes.Length) {
            $read = $stream.Read($bytes, $offset, $bytes.Length - $offset)
            if ($read -eq 0) { throw 'Capture specification changed while it was being read.' }
            $offset += $read
        }
        if ($stream.ReadByte() -ne -1) {
            throw "Capture specification exceeds the $maxSerializedBytes-byte limit."
        }
    }
    finally {
        $stream.Dispose()
    }

    $actualSha256 = [Convert]::ToHexString(
        [System.Security.Cryptography.SHA256]::HashData($bytes)).ToLowerInvariant()
    if ($actualSha256 -cne $ExpectedSha256.ToLowerInvariant()) {
        throw 'Capture specification content does not match the digest supplied by the parent.'
    }

    $strictUtf8 = [System.Text.UTF8Encoding]::new($false, $true)
    return $strictUtf8.GetString($bytes) | ConvertFrom-Json
}

function Get-Utf16PrefixLength([string]$Text, [int]$MaximumLength) {
    if ($MaximumLength -gt 0 -and $MaximumLength -lt $Text.Length -and
        [char]::IsHighSurrogate($Text[$MaximumLength - 1]) -and
        [char]::IsLowSurrogate($Text[$MaximumLength])) {
        return $MaximumLength - 1
    }

    return $MaximumLength
}

function Get-AllowlistedEnvironment {
    $variables = [ordered]@{}
    $allowlist = @(
        'COMPlus_ReadyToRun',
        'COMPlus_TC_QuickJit',
        'COMPlus_TC_QuickJitForLoops',
        'COMPlus_TieredCompilation',
        'DOTNET_ReadyToRun',
        'DOTNET_TC_QuickJit',
        'DOTNET_TC_QuickJitForLoops',
        'DOTNET_TieredCompilation')
    foreach ($name in $allowlist) {
        $value = [Environment]::GetEnvironmentVariable($name)
        if ($null -ne $value) { $variables[$name] = $value }
    }

    $serialized = $variables | ConvertTo-Json -Compress
    return [ordered]@{
        variables = $variables
        sha256    = Get-Sha256Text $serialized
    }
}

function Get-BoundedDiagnostic([string]$Text) {
    $trimmed = $Text.Trim()
    if ($trimmed.Length -le 2048) { return $trimmed }
    $prefixLength = Get-Utf16PrefixLength $trimmed 2048
    return $trimmed.Substring(0, $prefixLength) + '... [truncated]'
}

function Get-TraceFileName([string]$Name) {
    $extension = '.etl'
    if ($Name.Length + $extension.Length -le $maxTraceFileNameLength) {
        return "$Name$extension"
    }

    $hash = (Get-Sha256Text $Name).Substring(0, 16)
    $prefixLength = $maxTraceFileNameLength - $extension.Length - $hash.Length - 1
    $prefixLength = Get-Utf16PrefixLength $Name $prefixLength
    return "$($Name.Substring(0, $prefixLength))-$hash$extension"
}

function Write-BoundedUtf8File([string]$Path, [string]$Content) {
    $encoding = [System.Text.UTF8Encoding]::new($false)
    $bytes = $encoding.GetBytes($Content)
    if ($bytes.Length -ge $maxSerializedBytes) {
        throw "Capture manifest is $($bytes.Length) UTF-8 bytes; it must be under the 16 MiB durable manifest safety limit. Split the capture into fewer scenarios or shorten its exact arguments."
    }

    [System.IO.File]::WriteAllBytes($Path, $bytes)
}

function Assert-ValidScenarioName([string]$Name) {
    if ([string]::IsNullOrWhiteSpace($Name)) { throw 'Every scenario needs a Name.' }
    if ($Name.Length -gt $maxCaseIdLength) {
        throw "Scenario name '$Name' exceeds the $maxCaseIdLength-character manifest case-id limit."
    }
    if ($Name.IndexOfAny([char[]]'<>:"/\|?*') -ge 0 -or $Name.ToCharArray().Where({ [char]::IsControl($_) }).Count -gt 0) {
        throw "Scenario name '$Name' contains characters that are not valid in a Windows trace filename."
    }
    if ($Name.EndsWith('.') -or $Name.EndsWith(' ')) {
        throw "Scenario name '$Name' may not end with a dot or space because Windows removes those characters from filenames."
    }
    if ($Name -match '^(?i:CON|PRN|AUX|NUL|COM[1-9\u00B9\u00B2\u00B3]|LPT[1-9\u00B9\u00B2\u00B3])(?:\.|$)') {
        throw "Scenario name '$Name' is reserved by Windows and cannot name a trace file."
    }
}

# Normalizes the caller's matrix into plain objects that survive the JSON round-trip to the
# elevated child, failing on the mistakes that would otherwise surface as a confusing
# capture error much later.
function Resolve-Scenarios([object[]]$Entries) {
    if (-not $Entries -or $Entries.Count -eq 0) {
        throw 'Supply at least one -Scenario, for example @{ Name = ''version''; Command = ''dotnet''; Arguments = ''--version'' }.'
    }
    if ($Entries.Count -gt $maxCaptureCases) {
        throw "A command capture may contain at most $maxCaptureCases scenarios, matching the manifest reader limit."
    }

    $names = New-Object 'System.Collections.Generic.HashSet[string]' ([StringComparer]::OrdinalIgnoreCase)
    $resolved = foreach ($entry in $Entries) {
        $name = [string]$entry.Name
        $requestedCommand = if ($entry.RequestedCommand) { [string]$entry.RequestedCommand } else { [string]$entry.Command }
        Assert-ValidScenarioName $name
        if ([string]::IsNullOrWhiteSpace($requestedCommand)) { throw "Scenario '$name' needs a Command." }
        if (-not $names.Add($name)) {
            throw "Scenario name '$name' is used more than once; names are the identity diff pairs on."
        }

        $normalizedKind = [string]$entry.ArgumentsKind
        $hasArguments = if ($entry -is [System.Collections.IDictionary]) {
            $entry.Contains('Arguments')
        }
        else {
            $null -ne $entry.PSObject.Properties['Arguments']
        }
        $hasArgumentList = if ($entry -is [System.Collections.IDictionary]) {
            $entry.Contains('ArgumentList')
        }
        else {
            $null -ne $entry.PSObject.Properties['ArgumentList']
        }
        if (-not $normalizedKind -and $hasArguments -and $hasArgumentList) {
            throw "Scenario '$name' cannot specify both Arguments and ArgumentList."
        }

        $argumentsKind = if ($normalizedKind) {
            $normalizedKind
        }
        elseif ($hasArgumentList) {
            'argumentList'
        }
        else {
            'legacyCommandLine'
        }
        if ($argumentsKind -notin @('legacyCommandLine', 'argumentList')) {
            throw "Scenario '$name' has unsupported argument provenance '$argumentsKind'."
        }

        [string[]]$argumentList = @()
        if ($argumentsKind -eq 'argumentList' -and $null -ne $entry.ArgumentList) {
            foreach ($argument in @($entry.ArgumentList)) {
                if ($null -eq $argument) { throw "Scenario '$name' ArgumentList cannot contain null." }
                $argumentList += [string]$argument
            }
        }
        $arguments = if ($argumentsKind -eq 'argumentList') {
            Join-WindowsCommandLine $argumentList
        }
        else {
            [string]$entry.Arguments
        }
        $commandToResolve = if ($normalizedKind -and $entry.Command) { [string]$entry.Command } else { $requestedCommand }
        $executable = Resolve-ExecutableIdentity $commandToResolve
        if ($normalizedKind -and $entry.ExecutableSha256 -and
            $executable.sha256 -cne [string]$entry.ExecutableSha256) {
            throw "Scenario '$name' executable content does not match the non-elevated capture specification."
        }

        [pscustomobject]@{
            Name             = $name
            RequestedCommand = $requestedCommand
            Command          = $executable.path
            ExecutableSha256 = $executable.sha256
            ArgumentsKind    = $argumentsKind
            Arguments        = $arguments
            ArgumentList     = if ($argumentsKind -eq 'argumentList') { ,@($argumentList) } else { $null }
            TraceFileName    = Get-TraceFileName $name
        }
    }

    return @($resolved)
}

# The launched command inherits filtrace's stdout, so its own output is interleaved with
# the JSON result - a scenario that prints anything would otherwise be dropped as
# unparseable and vanish from the manifest. The result is a single line written last, so
# scan back a line at a time; going character by character would work too but records a
# failed parse per attempt in the transcript, which reads like a broken run.
function Get-TrailingJson([string]$Text) {
    $lines = $Text -split "`r?`n"
    for ($line = $lines.Length - 1; $line -ge 0; $line--) {
        $start = $lines[$line].IndexOf('{')
        while ($start -ge 0) {
            try {
                return $lines[$line].Substring($start) | ConvertFrom-Json
            }
            catch {
                $start = $lines[$line].IndexOf('{', $start + 1)
            }
        }
    }

    return $null
}

function Get-RequiredInvocationInt32([object]$Invocation, [string]$PropertyName, [string]$ScenarioName) {
    $property = $Invocation.PSObject.Properties[$PropertyName]
    if ($null -eq $property -or
        (($property.Value -isnot [int]) -and ($property.Value -isnot [long])) -or
        [long]$property.Value -lt [int]::MinValue -or
        [long]$property.Value -gt [int]::MaxValue) {
        throw "Scenario '$ScenarioName' collect result has an invocation without an integer '$PropertyName'."
    }

    return [int]$property.Value
}

function Get-RequiredInvocationTimestamp([object]$Invocation, [string]$PropertyName, [string]$ScenarioName) {
    $property = $Invocation.PSObject.Properties[$PropertyName]
    $timestamp = [DateTimeOffset]::MinValue
    $text = if ($null -eq $property) {
        $null
    }
    elseif ($property.Value -is [DateTimeOffset] -or $property.Value -is [DateTime]) {
        $property.Value.ToString('O', [Globalization.CultureInfo]::InvariantCulture)
    }
    elseif ($property.Value -is [string]) {
        $property.Value
    }
    else {
        $null
    }
    if ($null -eq $property -or
        $null -eq $text -or
        -not [DateTimeOffset]::TryParse(
            $text,
            [Globalization.CultureInfo]::InvariantCulture,
            [Globalization.DateTimeStyles]::RoundtripKind,
            [ref]$timestamp)) {
        throw "Scenario '$ScenarioName' collect result has an invocation without a round-trip '$PropertyName' timestamp."
    }

    return $timestamp
}

function Assert-ValidCollectResult([object]$Result, [int]$ExpectedCount, [string]$ScenarioName) {
    if ($null -eq $Result) {
        throw "Scenario '$ScenarioName' produced no collect result object."
    }

    $invocationsProperty = $Result.PSObject.Properties['invocations']
    if ($null -eq $invocationsProperty -or
        $null -eq $invocationsProperty.Value -or
        $invocationsProperty.Value -isnot [System.Array]) {
        throw "Scenario '$ScenarioName' collect result has no invocations array."
    }

    $invocations = @($invocationsProperty.Value)
    if ($invocations.Count -ne $ExpectedCount) {
        throw "Scenario '$ScenarioName' collect result has $($invocations.Count) invocations; expected $ExpectedCount."
    }

    $ordinals = [System.Collections.Generic.HashSet[int]]::new()
    for ($index = 0; $index -lt $invocations.Count; $index++) {
        $invocation = $invocations[$index]
        if ($null -eq $invocation) {
            throw "Scenario '$ScenarioName' collect result contains a null invocation."
        }

        $ordinal = Get-RequiredInvocationInt32 $invocation 'ordinal' $ScenarioName
        if ($ordinal -le 0 -or -not $ordinals.Add($ordinal) -or $ordinal -ne $index + 1) {
            throw "Scenario '$ScenarioName' collect result invocation ordinals must be unique and sequential from 1."
        }

        $processId = Get-RequiredInvocationInt32 $invocation 'processId' $ScenarioName
        if ($processId -le 0) {
            throw "Scenario '$ScenarioName' collect result invocation processId must be positive."
        }

        [void](Get-RequiredInvocationInt32 $invocation 'exitCode' $ScenarioName)
        $startedUtc = Get-RequiredInvocationTimestamp $invocation 'startedUtc' $ScenarioName
        $stoppedUtc = Get-RequiredInvocationTimestamp $invocation 'stoppedUtc' $ScenarioName
        if ($stoppedUtc -lt $startedUtc) {
            throw "Scenario '$ScenarioName' collect result invocation stoppedUtc precedes startedUtc."
        }
    }
}

if ($IsWindows -eq $false) {
    Write-Error 'ETW capture is Windows-only. Use dotnet-trace for an EventPipe capture on this OS.' -ErrorAction Continue
    exit 1
}

# The elevated child receives the matrix through a file rather than the command line: a
# scenario's arguments can contain quotes and spaces that would not survive Start-Process
# joining an argument array into one string.
if ($SpecPath) {
    $spec = Read-AuthenticatedSpec $SpecPath $ExpectedSpecSha256
    $scenarios = Resolve-Scenarios @($spec.scenarios)

    # A spec written by an older version omits fields this one reads. Assigning a missing
    # value coerces $null through the parameter's declared type - 0 for a double, '' for a
    # validated string - and the validation attribute, which re-runs on every assignment,
    # then rejects it. That failure lands in the elevated child, where it surfaces as a
    # message naming only the variable. Keeping the bound value degrades to the default
    # instead.
    if ($null -ne $spec.iterations) { $Iterations = $spec.iterations }
    if ($spec.profile) { $CaptureProfile = $spec.profile }
    if ($null -ne $spec.cpuSampleMSec) { $CpuSampleMSec = $spec.cpuSampleMSec }

    # Unvalidated and optional: '' is their natural unset value, so a missing field needs
    # no guard.
    $OutputDirectory = $spec.outputDirectory
    $SymbolsDirectory = $spec.symbolsDirectory
    $FiltracePath = $spec.filtracePath
    $workingDirectory = if ($spec.workingDirectory) {
        [System.IO.Path]::GetFullPath([string]$spec.workingDirectory)
    }
    else {
        $invocationWorkingDirectory
    }
    $expectedFiltraceIdentity = $spec.filtrace
}
else {
    $scenarios = Resolve-Scenarios $Scenario
    $workingDirectory = $invocationWorkingDirectory
    if (-not $OutputDirectory) {
        $runStamp = (Get-Date).ToUniversalTime().ToString('yyyyMMdd-HHmmss')
        $OutputDirectory = Join-Path $workingDirectory "perf-traces/command-$runStamp"
    }
}

$workingDirectory = [System.IO.Path]::GetFullPath($workingDirectory)
if (-not (Test-Path -LiteralPath $workingDirectory -PathType Container)) {
    throw "Working directory '$workingDirectory' does not exist."
}
$runDirectory = [System.IO.Path]::TrimEndingDirectorySeparator(
    [System.IO.Path]::GetFullPath($OutputDirectory))
if (Test-Path -LiteralPath $runDirectory) {
    if (-not $SpecPath) {
        $existingRunEntry = Get-ChildItem -LiteralPath $runDirectory -Force | Select-Object -First 1
        if ($null -ne $existingRunEntry) {
            throw "OutputDirectory '$runDirectory' is not empty; choose a new command-capture run directory."
        }
    }
    else {
        $ownedHandoffPaths = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
        [void]$ownedHandoffPaths.Add([System.IO.Path]::GetFullPath($SpecPath))
        if ($LogFile) { [void]$ownedHandoffPaths.Add([System.IO.Path]::GetFullPath($LogFile)) }
        $staleRunEntry = Get-ChildItem -LiteralPath $runDirectory -Force |
            Where-Object { -not $ownedHandoffPaths.Contains($_.FullName) } |
            Select-Object -First 1
        if ($null -ne $staleRunEntry) {
            throw "OutputDirectory '$runDirectory' contains stale artifacts outside this elevation handoff."
        }
    }
}
New-Item -ItemType Directory -Force -Path $runDirectory | Out-Null
$filtraceIdentity = Get-FiltraceIdentity $FiltracePath
if ($null -ne $expectedFiltraceIdentity) {
    foreach ($field in @('path', 'sha256', 'version')) {
        if ([string]$filtraceIdentity[$field] -cne [string]$expectedFiltraceIdentity.$field) {
            throw "The elevated filtrace $field does not match the non-elevated capture specification."
        }
    }
}
$filtrace = $filtraceIdentity.path

if (-not (Test-Elevated)) {
    # One elevation for the whole matrix. Elevating per scenario would prompt once per
    # command and leave a partially captured run behind on the first refusal.
    $spec = [ordered]@{
        scenarios        = $scenarios
        iterations       = $Iterations
        profile          = $CaptureProfile
        cpuSampleMSec    = $CpuSampleMSec
        outputDirectory  = $runDirectory
        workingDirectory = $workingDirectory
        symbolsDirectory = $SymbolsDirectory
        filtracePath      = $filtrace
        filtrace          = $filtraceIdentity
    } | ConvertTo-Json -Depth 5
    $specFile = Join-Path $runDirectory 'scenarios.json'
    $encoding = New-Object System.Text.UTF8Encoding($false)
    $specBytes = $encoding.GetBytes($spec)
    if ($specBytes.Length -gt $maxSerializedBytes) {
        throw "Capture specification exceeds the $maxSerializedBytes-byte limit."
    }
    $expectedSpecSha256 = [Convert]::ToHexString(
        [System.Security.Cryptography.SHA256]::HashData($specBytes)).ToLowerInvariant()
    [System.IO.File]::WriteAllBytes($specFile, $specBytes)

    $childLog = Join-Path $runDirectory 'capture.log'
    Write-Host "Elevating to capture $($scenarios.Count) scenario(s) (a UAC prompt will appear)..." -ForegroundColor Yellow

    $childArguments = @(
        '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $PSCommandPath,
        '-SpecPath', $specFile, '-ExpectedSpecSha256', $expectedSpecSha256,
        '-LogFile', $childLog)
    $argList = @($childArguments | ForEach-Object { ConvertTo-WindowsCommandLineArgument $_ })
    $hostExe = (Get-Process -Id $PID).Path
    if ([System.IO.Path]::GetFileNameWithoutExtension($hostExe) -notin @('pwsh', 'powershell')) {
        Write-Error "The current host '$hostExe' cannot perform the elevated relaunch." -ErrorAction Continue
        exit 1
    }

    # Do NOT pass -Wait. With -Verb RunAs it can fail to release after the child closes,
    # hanging this runner; wait on the process object with a bounded timeout instead so a
    # lost handle degrades to a timeout rather than a hang.
    $proc = $null
    $childExit = 1
    try {
        $proc = Start-Process -FilePath $hostExe -Verb RunAs -PassThru -WorkingDirectory $workingDirectory -ArgumentList $argList
        if ($null -eq $proc) {
            Write-Error 'Elevated relaunch returned no process handle; check for a blocked UAC prompt.' -ErrorAction Continue
        }
        else {
            $waitMs = [int][Math]::Min([long]$ElevatedTimeoutSeconds * 1000, [int]::MaxValue)
            $exited = $false
            try { $exited = $proc.WaitForExit($waitMs) } catch { $exited = $false }

            if (Test-Path -LiteralPath $childLog) {
                Write-Host "`n--- capture output ($childLog) ---" -ForegroundColor Cyan
                Get-Content -LiteralPath $childLog -Tail 200
            }

            if (-not $exited) {
                Write-Error "The elevated capture did not finish within $ElevatedTimeoutSeconds s; the child may still be running. See $childLog." -ErrorAction Continue
            }
            else {
                try {
                    $observedExitCode = $proc.ExitCode
                    if ($null -ne $observedExitCode) { $childExit = [int]$observedExitCode }
                }
                catch { $childExit = 1 }
            }
        }
    }
    catch {
        Write-Error "Elevated relaunch failed: $($_.Exception.Message)" -ErrorAction Continue
    }
    finally {
        if ($null -ne $proc) { $proc.Dispose() }
    }
    exit $childExit
}

# Elevated from here: run the matrix and write the manifest. The transcript is what the
# non-elevated parent surfaces once this window closes, so it has to start before any work.
$transcript = $LogFile ? $LogFile : (Join-Path $runDirectory 'capture.log')
try { Start-Transcript -Path $transcript -Force | Out-Null } catch { }
$startedUtc = [DateTimeOffset]::UtcNow

Set-Location -LiteralPath $workingDirectory

# Fail on a tool that predates the options this depends on, rather than letting every
# scenario fail one at a time with an unrecognized-option message.
$collectHelp = & $filtrace collect --help 2>&1 | Out-String
$collectHelpExitCode = $LASTEXITCODE
if ($collectHelpExitCode -ne 0) {
    Write-Error "Resolved filtrace '$filtrace' failed collect --help with exit $collectHelpExitCode." -ErrorAction Continue
    exit 1
}
foreach ($required in '--iterations', '--format', '--launch-args') {
    if ($collectHelp -notmatch [regex]::Escape($required)) {
        Write-Error "This filtrace build's collect verb has no $required option; update the tool." -ErrorAction Continue
        exit 1
    }
}

$cases = @()
$failedCases = @()
$warnings = @()
foreach ($item in $scenarios) {
    $tracePath = [System.IO.Path]::GetFullPath((Join-Path $runDirectory $item.TraceFileName))
    if (-not [System.IO.Path]::GetDirectoryName($tracePath).Equals($runDirectory, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Scenario '$($item.Name)' resolved outside the command-capture run directory."
    }
    Write-Host "Capturing '$($item.Name)': $($item.Command) $($item.Arguments) x$Iterations" -ForegroundColor Cyan

    $collectArgs = @(
        'collect',
        '--launch', $item.Command,
        '--output', $tracePath,
        '--profile', $CaptureProfile,
        '--cpu-ms', $CpuSampleMSec,
        '--iterations', $Iterations,
        '--format', 'json')
    if ($item.Arguments) { $collectArgs += @('--launch-args', $item.Arguments) }

    # The JSON result is what carries each launch; the human summary would have to be
    # parsed back, which is not a contract worth depending on.
    $raw = & $filtrace @collectArgs 2>&1 | Out-String
    $collectExitCode = $LASTEXITCODE
    $commandProvenance = [ordered]@{
        executable       = [ordered]@{
            requested = $item.RequestedCommand
            path      = $item.Command
            sha256    = $item.ExecutableSha256
        }
        arguments        = [ordered]@{
            kind         = $item.ArgumentsKind
            commandLine  = $item.Arguments
            argumentList = if ($item.ArgumentsKind -eq 'argumentList') { ,@($item.ArgumentList) } else { $null }
        }
        workingDirectory = $workingDirectory
    }
    if ($collectExitCode -ne 0) {
        $diagnostic = Get-BoundedDiagnostic $raw
        $warnings += "Scenario '$($item.Name)' failed (exit $collectExitCode): $diagnostic"
        $failedCases += [ordered]@{
            id              = $item.Name
            status          = 'collectFailed'
            trace           = $tracePath
            command         = $commandProvenance
            collectExitCode = $collectExitCode
            diagnostic      = $diagnostic
        }
        Write-Warning "Scenario '$($item.Name)' failed; continuing with the rest of the matrix."
        continue
    }

    $result = (Get-TrailingJson $raw)?.result
    try {
        Assert-ValidCollectResult $result $Iterations $item.Name
    }
    catch {
        $validationError = $_.Exception.Message
        $diagnostic = Get-BoundedDiagnostic "$validationError`n$raw"
        $warnings += $validationError
        $failedCases += [ordered]@{
            id              = $item.Name
            status          = 'invalidResult'
            trace           = $tracePath
            command         = $commandProvenance
            collectExitCode = $collectExitCode
            diagnostic      = $diagnostic
        }
        Write-Warning "$validationError Continuing with the rest of the matrix."
        continue
    }

    $case = [ordered]@{
        id               = $item.Name
        benchmark        = $item.Name
        parameters       = ''
        benchmarkDisplay = $item.Name
        trace            = $tracePath
        command          = $commandProvenance
        # What this case actually sampled at, which is the requested interval only when
        # the machine honored it.
        cpuSampleMSec    = if ($result.cpuSample) { $result.cpuSample.effectiveMSec } else { $CpuSampleMSec }
        invocations      = @($result.invocations | ForEach-Object {
                [ordered]@{
                    ordinal    = $_.ordinal
                    processId  = $_.processId
                    exitCode   = $_.exitCode
                    startedUtc = $_.startedUtc
                    stoppedUtc = $_.stoppedUtc
                }
            })
    }

    # Omitted rather than written empty: an unset [string] parameter is "", and the reader
    # rejects an empty optional field rather than treating it as absent.
    if ($SymbolsDirectory) { $case['symbolsDirectory'] = $SymbolsDirectory }
    $cases += $case

    # Windows honors the interval only inside the profile source's bounds and reports no
    # error outside them, so a clamp is only visible if the capture records it. Every
    # weight in the trace is scaled to the effective interval, not the requested one.
    if ($result.cpuSample) {
        $effectiveMSec = $result.cpuSample.effectiveMSec
        if ($result.cpuSample.clamped) {
            # Four decimals or the floor renders as 0.12, losing the distinction between
            # 0.1221 and 0.125 that the interval reporting exists to make.
            $warnings += ("Scenario '{0}' requested a {1:0.####} ms sample interval but this machine honors {2:0.####} to {3:0.####} ms; it sampled at {4:0.####} ms." -f `
                    $item.Name, $result.cpuSample.requestedMSec, $result.cpuSample.minimumMSec, $result.cpuSample.maximumMSec, $effectiveMSec)
            Write-Warning ("Scenario '{0}' sampled at {1:0.####} ms, not the requested {2:0.####} ms." -f `
                    $item.Name, $effectiveMSec, $result.cpuSample.requestedMSec)
        }
    }
}

$manifest = [ordered]@{
    schemaVersion            = 2
    kind                     = 'command'
    startedUtc               = $startedUtc.ToString('O')
    completedUtc             = [DateTimeOffset]::UtcNow.ToString('O')
    profile                  = $CaptureProfile
    iterations               = $Iterations
    # The run's setting, alongside profile and iterations. What each case actually got is
    # its own cpuSampleMSec, which differs whenever the machine clamped the request.
    requestedCpuSampleMSec   = $CpuSampleMSec
    workingDirectory         = $workingDirectory
    filtrace                 = $filtraceIdentity
    environment              = Get-AllowlistedEnvironment
    cases                    = $cases
    failedCases              = $failedCases
    warnings                 = $warnings
}

# A single executable retains the legacy manifest-wide name as a convenience. Mixed
# executable manifests use each case's exact invocation roots; batch and diff consume
# those ids directly, while descendants remain authoritative in the ETW process graph.
$executables = @($scenarios | ForEach-Object { [System.IO.Path]::GetFileNameWithoutExtension($_.Command) } | Sort-Object -Unique)
if ($executables.Count -eq 1) {
    $manifest['process'] = $executables[0]
}

$manifestPath = Join-Path $runDirectory 'manifest.json'
$manifestJson = $manifest | ConvertTo-Json -Depth 8
Write-BoundedUtf8File $manifestPath $manifestJson

if ($cases.Count -eq 0) {
    Write-Error "No scenario captured successfully; failure diagnostics were written to $manifestPath." -ErrorAction Continue
    $warnings | ForEach-Object { Write-Host $_ }
    try { Stop-Transcript | Out-Null } catch { }
    exit 1
}

Write-Host ""
Write-Host "Captured $($cases.Count) scenario(s) -> $manifestPath" -ForegroundColor Green
if ($warnings.Count -gt 0) {
    # Not all failures: this channel also carries advisories from runs that succeeded,
    # such as a clamped sample interval or a matrix with no single process scope.
    Write-Host "$($warnings.Count) warning(s):" -ForegroundColor Yellow
    $warnings | ForEach-Object { Write-Host "  $_" -ForegroundColor Yellow }
}

Write-Host ""
Write-Host "Next-step filtrace commands:"
Write-Host "  filtrace batch `"$manifestPath`""
Write-Host "  filtrace diff `"<baseline>/manifest.json`" `"$manifestPath`""

try { Stop-Transcript | Out-Null } catch { }
