<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Filtrace.Benchmarks</RootNamespace>
    <AssemblyName>Filtrace.Benchmarks</AssemblyName>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <ProjectReference Include="..\..\src\Filtrace.Core\Filtrace.Core.csproj" />
    <ProjectReference Include="..\..\src\Filtrace\Filtrace.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Filtrace.Cli.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\tests\Filtrace.Core.Tests\Fixtures\activity.nettrace" Link="Fixtures\activity.nettrace">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\tests\Filtrace.Core.Tests\Fixtures\alloc.nettrace" Link="Fixtures\alloc.nettrace">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\tests\Filtrace.Core.Tests\Fixtures\exceptions.nettrace" Link="Fixtures\exceptions.nettrace">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\tests\Filtrace.Core.Tests\Fixtures\jit.nettrace" Link="Fixtures\jit.nettrace">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\tests\Filtrace.Core.Tests\Fixtures\threadpool.nettrace" Link="Fixtures\threadpool.nettrace">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
